# Generated by Django 4.2.20 on 2025-05-09 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='balance_date',
            field=models.DateField(default=datetime.date(2025, 5, 9), unique=True, verbose_name='Balance Date'),
        ),
    ]
